In [ ]:
## Code By Luis Gonzalez
## Debt by Country

In [5]:
# We will be using Pandas for reading al the relevant datasets.
import pandas as pd

In [9]:

df = pd.read_excel('WEO_Data.xlsx')
# We make a time range

In [10]:
df

,Country,1980,1981,1982,1983,1984,1985,1986,1987,1988,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,Estimates Start After
0,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,68.170,63.749,60.354,59.031,56.800,54.509,52.105,49.933,50.251,2018.0
1,Algeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.327,21.598,26.540,37.342,40.697,44.246,46.843,48.201,51.032,2018.0
2,Argentina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,53.100,56.600,86.000,89.400,0.930,95.000,93.000,92.000,92.000,NaN
3,Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18.843,18.760,20.162,21.340,21.547,20.687,19.435,18.170,17.047,2018.0
4,Austria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,57.135,55.910,50.467,48.179,45.956,44.015,41.837,39.562,37.317,2018.0
5,Barbados,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,148.226,157.097,124.566,114.292,108.218,101.693,95.577,90.218,85.661,2019.0
6,Belgium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,92.215,89.587,88.448,87.733,86.853,86.126,85.415,84.483,83.523,2018.0
7,Bolivia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30.477,35.402,41.103,47.133,51.638,55.136,57.591,59.023,59.466,2017.0
8,Bosnia and Herzegovina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,36.511,30.399,24.114,24.353,24.131,24.248,24.093,24.605,24.328,2018.0
9,Botswana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-3.178,-4.620,-3.328,0.742,3.291,5.039,6.100,6.258,5.361,2019.0
10,Brazil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,46.176,51.638,54.154,58.095,61.046,62.246,63.593,63.910,64.551,2018.0
11,Bulgaria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.453,10.518,9.145,8.457,7.767,7.201,6.713,6.266,5.837,2018.0
12,Cabo Verde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,121.770,120.803,116.810,116.250,112.083,106.614,100.432,94.549,88.933,2018.0
13,Cameroon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,31.160,34.241,36.626,37.818,37.462,37.342,37.223,36.924,36.436,2017.0
14,Canada,14.191,13.295,18.856,25.152,29.004,34.542,38.847,38.476,37.572,...,28.802,27.581,26.770,26.399,25.675,24.829,23.966,23.053,22.078,2018.0
15,Chile,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.941,4.401,5.687,8.487,10.834,12.410,13.135,13.573,13.761,2018.0
16,China,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,44.180,46.790,50.460,55.360,59.510,63.230,66.680,69.660,72.420,NaN
17,Colombia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,38.611,38.979,41.539,41.429,40.157,38.542,37.145,35.816,34.066,2018.0
18,Croatia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,68.533,65.877,62.715,NaN,NaN,NaN,NaN,NaN,NaN,2018.0
19,Cyprus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,86.891,79.497,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018.0
20,Czech Republic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,25.123,21.722,19.878,NaN,NaN,NaN,NaN,NaN,NaN,2018.0
21,Denmark,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.506,14.565,13.760,13.157,12.688,12.354,12.048,11.674,11.141,2018.0
22,Djibouti,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,43.710,46.049,46.951,46.402,44.875,44.166,41.878,39.862,38.122,2018.0
23,Dominican Republic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,38.500,40.303,41.409,43.354,43.699,43.986,44.228,44.444,44.889,2018.0
24,Egypt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,88.188,93.884,81.331,75.436,75.676,73.528,72.416,71.979,69.354,2018.0
25,Estonia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-2.641,-1.581,-1.384,0.264,0.381,0.464,0.539,0.707,0.912,2018.0
26,Eswatini,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,17.452,22.475,31.315,37.167,38.988,41.793,45.759,50.136,55.214,2019.0
27,Ethiopia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,51.789,54.563,57.407,56.105,51.900,50.168,48.818,48.777,49.037,2018.0
28,Fiji,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,43.600,43.308,45.693,46.307,46.337,46.280,46.227,46.133,46.088,2018.0
29,Finland,62.466,61.906,57.103,53.906,53.628,56.145,57.742,57.727,60.364,...,21.481,22.139,24.187,24.121,24.343,24.658,24.835,24.850,24.753,2018.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,Pakistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,61.259,61.492,66.790,72.521,75.161,73.161,69.961,66.795,63.514,2018.0
68,Panama,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,34.882,35.320,37.406,39.361,39.992,39.671,39.096,38.507,37.938,2018.0
69,Paraguay,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15.603,15.947,18.351,20.953,20.490,20.072,19.861,19.620,19.625,2018.0
70,Peru,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.951,8.725,10.213,11.250,12.063,12.270,12.439,12.634,12.819,2018.0
71,Poland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,47.924,44.592,42.324,42.979,42.505,42.299,42.264,42.325,42.594,2018.0
72,Portugal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,120.050,116.526,114.142,112.094,108.352,105.278,101.514,97.617,93.865,2018.0
73,Romania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,27.719,28.330,28.291,29.146,30.404,31.739,33.110,34.377,35.378,2018.0
74,Russia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.900,15.500,14.600,14.600,17.200,18.500,21.000,NaN,NaN,2018.0
75,Saudi Arabia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-17.115,-7.679,-0.087,6.763,13.709,21.938,28.744,34.704,39.425,2018.0
76,Serbia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,66.516,56.588,52.632,50.689,47.616,44.742,42.342,40.069,37.716,2018.0
77,Seychelles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,50.897,48.473,43.613,41.977,39.210,36.539,33.707,31.334,29.773,2018.0
78,Slovenia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,52.396,51.958,46.030,NaN,NaN,NaN,NaN,NaN,NaN,2018.0
79,Solomon Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-6.401,-3.413,-2.926,-0.139,2.454,4.872,9.543,15.049,19.345,2017.0
80,South Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,45.406,47.770,51.049,55.313,60.276,64.172,67.479,70.641,73.722,2018.0
81,Spain,NaN,NaN,NaN,NaN,NaN,24.803,27.844,28.428,29.044,...,86.123,84.700,83.101,82.831,82.058,81.242,80.535,79.773,79.010,2018.0
82,St. Vincent and the Grenadines,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,79.630,70.641,71.381,69.170,67.650,65.987,64.534,63.258,62.229,2018.0
83,Sweden,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.832,6.095,5.609,5.125,4.590,4.140,3.716,3.431,3.001,2018.0
84,Switzerland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,22.714,21.527,20.840,18.943,17.625,16.318,15.022,13.699,12.442,2017.0
85,Syria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2009.0
86,Taiwan Province of China,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,34.288,33.609,33.179,31.700,30.381,28.866,27.340,25.752,24.142,2018.0
87,Trinidad and Tobago,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-7.465,-9.288,-9.191,-5.094,-1.839,1.575,5.401,8.999,12.344,2018.0
88,Turkey,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,23.436,22.279,24.118,24.448,24.882,25.801,27.119,28.475,29.515,2018.0
89,United Arab Emirates,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20.200,19.700,18.600,18.600,25.000,22.000,18.900,NaN,NaN,2018.0
90,United Kingdom,40.903,43.156,42.946,41.505,42.021,41.687,40.610,37.882,34.116,...,78.842,77.519,77.469,76.070,75.419,75.173,74.888,74.403,73.891,2018.0
91,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,81.586,81.562,80.034,80.932,83.917,85.990,89.780,92.269,94.429,2018.0
92,Uruguay,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,49.700,49.491,52.383,53.020,53.173,53.174,54.417,55.470,55.951,2018.0
93,Venezuela,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,31.400,23.000,23.000,23.000,50.000,60.000,65.000,NaN,NaN,2018.0
94,Yemen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,78.516,83.338,64.115,55.750,56.366,43.163,35.769,30.179,22.263,2017.0
95,Zambia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,51.331,55.921,67.028,77.729,82.437,85.543,86.150,86.258,85.454,2017.0
96,Greece,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,173.500,176.200,181.200,175.000,182.500,183.200,183.600,157.170,154.130,2018.0

In [12]:
df = df.fillna(0)

In [13]:
df.to_csv('DebtByCountry.csv',index=False)