## Code By Luis Gonzalez
## Python code to create Top 10 Country Oil Production (1982-2019) Dataviz


**Disclaimer:** My varible names could have been improved.

Top 10 Country Oil Production (1982-2019) 

This video shows the Top 10 countries in terms of Crude Oil Production from 1982 until 2019. This video gives a great visual understanding of who the leading players are in the global market. However, this might change drastically in the next years as the Oil Market is experiencing a high level of volatility today (2020).   

Source: U.S. Energy Information Administration (EIA) (2020). Petroleum and other liquids Retrieved from https://bit.ly/2YoFdw1   

Follow my Github for a Step-By-Step guide on how to build these types of visuals. (https://github.com/LuisEGV)

In [104]:
# We will be using Pandas for reading al the relevant datasets.
import pandas as pd

In [105]:
# Here we read the data from the Energy Dataset
df = pd.read_excel('CrudeOil.xls',header=None)
# We make a time range
time = list(range(1973, 2019))

In [164]:
# Now we turn the data range to a pandas readable format
TimeList = pd.DataFrame(time)

In [68]:
# Now we make a list with all the countries from the original datast
countries = []
for i in range(0,len(df[0])):
    if i%8 == 0:
        countries.append(df[0][i])

In [78]:
# Here we can see the origianl dataset. We can see that its very messy
df

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,World,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Production,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Total petroleum and other liquids (Mb/d),NaN,NaN,NaN,NaN,NaN,NaN,NaN,63987.8,60602,...,88558.5,89035.9,91089.5,91686.3,94283.4,97104.3,97601.3,98114.2,100784,100631
3,"Crude oil, NGPL, and other liquids...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,63092.9,59785.5,...,86204.2,86626.3,88655.3,89174.1,91730.6,94476.6,94934.3,95450.7,98087,97990.3
4,Crude oil including lease cond...,55678.9,55716.5,52828.4,57344.4,59706.9,60157.9,62674.2,59557.6,56049,...,74893.8,74920.7,76399.3,76474.8,78390,80762.3,80847.5,81095.9,82923.3,82274.6
5,NGPL (Mb/d),NaN,NaN,NaN,NaN,NaN,NaN,NaN,3395.29,3574.69,...,8638.22,8851.43,9211,9390.93,9836.68,10122.9,10313.2,10610.1,11191.2,11608.6
6,Other liquids (Mb/d),NaN,NaN,NaN,NaN,NaN,NaN,NaN,89,105,...,2672.09,2854.11,3045.02,3308.38,3503.93,3591.44,3773.56,3744.73,3972.49,4107.11
7,Refinery processing gain (Mb/d),NaN,NaN,NaN,NaN,NaN,NaN,NaN,887.7,802.9,...,2354.38,2409.64,2434.26,2512.27,2552.76,2627.63,2667.01,2663.44,2696.94,2640.63
8,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Production,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Total petroleum and other liquids (Mb/d),NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0
11,"Crude oil, NGPL, and other liquids...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0
12,Crude oil including lease cond...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0
13,NGPL (Mb/d),NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0
14,Other liquids (Mb/d),NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0
15,Refinery processing gain (Mb/d),NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0
16,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Production,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Total petroleum and other liquids (Mb/d),NaN,NaN,NaN,NaN,NaN,NaN,NaN,44,44,...,10.8708,15.5731,16.8471,17.0162,20.5868,20.2306,22.8176,16.069,15.6553,14.5649
19,"Crude oil, NGPL, and other liquids...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,44,44,...,10.8438,15.5151,16.8361,17.0082,20.5068,20.1616,22.7486,16,15.5863,14.4959
20,Crude oil including lease cond...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44,44,...,10.8438,15.5151,16.8361,17.0082,20.5068,20.1616,22.7486,16,15.5863,14.4959
21,NGPL (Mb/d),NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0
22,Other liquids (Mb/d),NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0
23,Refinery processing gain (Mb/d),NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,...,0.027,0.058,0.011,0.008,0.08,0.069,0.069,0.069,0.069,0.069
24,Algeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Production,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Total petroleum and other liquids (Mb/d),NaN,NaN,NaN,NaN,NaN,NaN,NaN,1143,1052,...,1881.05,1862.69,1875.23,1763.08,1722.34,1798.42,1698.79,1641.74,1577.08,1570.38
27,"Crude oil, NGPL, and other liquids...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,1142,1051,...,1880,1862,1874.24,1761.78,1720,1797,1697.36,1640.32,1575.66,1568.96
28,Crude oil including lease cond...,1097,1008.6,982.6,1075.1,1152.3,1231,1224,1105.91,1002.03,...,1540,1540,1532.24,1461.78,1420,1429,1348.36,1305.63,1258.66,1258.96
29,NGPL (Mb/d),NaN,NaN,NaN,NaN,NaN,NaN,NaN,36,49,...,340,322,342,300,300,368,349,334.685,317,310
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818,Total petroleum and other liquids (Mb/d),NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0
1819,"Crude oil, NGPL, and other liquids...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0
1820,Crude oil including lease cond...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0
1821,NGPL (Mb/d),NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0
1822,Other liquids (Mb/d),NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0
1823,Refinery processing gain (Mb/d),NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0
1824,Yemen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1825,Production,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1826,Total petroleum and other liquids (Mb/d),NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,...,281.108,216.76,169.001,130.804,125.101,47.893,21.9597,12.5533,33.8135,43.8135
1827,"Crude oil, NGPL, and other liquids...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,...,279.997,216.389,168.727,130.699,125.008,47.6,21.6667,12.2603,33.5205,43.5205
1828,Crude oil including lease cond...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,...,279.997,216.389,168.727,130.699,125.008,47.6,21.6667,12.2603,33.5205,43.5205
1829,NGPL (Mb/d),NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0
1830,Other liquids (Mb/d),NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0
1831,Refinery processing gain (Mb/d),NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,...,1.111,0.371,0.274,0.105,0.093,0.293,0.293,0.293,0.293,0.293
1832,Zambia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1833,Production,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1834,Total petroleum and other liquids (Mb/d),NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,...,0.17,0.186,0.199,0.164,0.186,0.17,0.17,0.17,0.17,0.17
1835,"Crude oil, NGPL, and other liquids...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0
1836,Crude oil including lease cond...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0
1837,NGPL (Mb/d),NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0
1838,Other liquids (Mb/d),NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0
1839,Refinery processing gain (Mb/d),NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,...,0.17,0.186,0.199,0.164,0.186,0.17,0.17,0.17,0.17,0.17
1840,Zimbabwe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1841,Production,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1842,Total petroleum and other liquids (Mb/d),NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,...,0,0,0.12,0.039,0.681,0.714,0.819,0.819,0.819,0.819
1843,"Crude oil, NGPL, and other liquids...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,...,0,0,0.12,0.039,0.681,0.714,0.819,0.819,0.819,0.819
1844,Crude oil including lease cond...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0
1845,NGPL (Mb/d),NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0
1846,Other liquids (Mb/d),NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,...,0,0,0.12,0.039,0.681,0.714,0.819,0.819,0.819,0.819
1847,Refinery processing gain (Mb/d),NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0

In [76]:
# Now we filter and only retrived the data for oil production for each country that we have in our "Country" list.
ProductionByCountry = []
for i in range(0,len(df[0])):
    if df[0][i] == "        Total petroleum and other liquids (Mb/d)":
        ProductionByCountry.append(df.iloc(0)[i])

In [118]:
# Now we concatonate the lists

df_test = ProductionByCountry[0]
for i in range(1,len(ProductionByCountry)):
    df_test = pd.concat([df_test,ProductionByCountry[i]],axis=1)

In [147]:
# Here we not transpose the data and drop a few unnecesary columns
Meh = df_test.T
Meh = Meh.drop([1,2,3,4,5,6,7], axis=1)

In [157]:
#Now we include our country list into our other dataset
CountriesList = pd.DataFrame(countries)
Meh['Countries'] = CountriesList

In [160]:
# Here is our new dataset
Meh

,0,8,9,10,11,12,13,14,15,16,...,39,40,41,42,43,44,45,46,47,Countries
2,Total petroleum and other liquids (Mb/d),63987.8,60602,58100.1,57929.3,59563.5,59156.1,61535,62101.3,64398.7,...,89035.9,91089.5,91686.3,94283.4,97104.3,97601.3,98114.2,100784,100631,Albania
10,Total petroleum and other liquids (Mb/d),0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Aruba
18,Total petroleum and other liquids (Mb/d),44,44,64,75,55,55,55,54,44,...,15.5731,16.8471,17.0162,20.5868,20.2306,22.8176,16.069,15.6553,14.5649,Belgium
26,Total petroleum and other liquids (Mb/d),1143,1052,1046,1018,1115,1142,1190,1200,1174,...,1862.69,1875.23,1763.08,1722.34,1798.42,1698.79,1641.74,1577.08,1570.38,Brazil
34,Total petroleum and other liquids (Mb/d),0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Cambodia
42,Total petroleum and other liquids (Mb/d),150,130,122,177,208,231,281,359,451,...,1765.03,1796.47,1814.03,1755.76,1827.92,1796.74,1706.43,1655.17,1511.63,Colombia
50,Total petroleum and other liquids (Mb/d),0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Cyprus
58,Total petroleum and other liquids (Mb/d),0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Egypt
66,Total petroleum and other liquids (Mb/d),508,513,507,504,498,485,471,472,492,...,763.104,722.697,706.127,716.351,708.683,708.77,676.228,678.56,690.058,Faroe Islands
74,Total petroleum and other liquids (Mb/d),--,--,--,--,--,--,--,--,--,...,0,0,0,0,0,0,0,0,0,French Guiana
82,Total petroleum and other liquids (Mb/d),--,--,--,--,--,--,0,0,0,...,2.822,0.68,0,0,0,0,0,0,0,Ghana
90,Total petroleum and other liquids (Mb/d),460,474,444,489,571,665,606,639,633,...,514.659,507.089,432.765,448.156,402.347,373.728,341.762,370.777,446.832,Guinea
98,Total petroleum and other liquids (Mb/d),30,28,29,28,27,25,25,24,27,...,36.9725,37.0095,27.9799,31.9039,33.0139,29.4152,29.2455,28.2236,27.6428,Iceland
106,Total petroleum and other liquids (Mb/d),--,--,--,--,--,--,--,--,--,...,993.261,931.756,880.825,856.876,858.177,843.546,800.682,808.482,789.868,Jamaica
114,Total petroleum and other liquids (Mb/d),57,55,53,52,51,49,53,52,53,...,47.487,55.165,60.993,64.1811,65.886,63.886,59.886,56.886,54.886,Kyrgyzstan
122,Total petroleum and other liquids (Mb/d),0,0,0,0.2,0.4,0.7,0.7,0.6,0.8,...,5.063,4.84867,4.156,4.127,4.105,4.105,3.77075,3.105,3.105,Luxembourg
130,Total petroleum and other liquids (Mb/d),0,0,1,1,2,2,1.9,1.2,1.2,...,1,1,1,1,1,1,1,1,1,Martinique
138,Total petroleum and other liquids (Mb/d),--,--,--,--,--,--,--,--,--,...,30.739,30.124,31.307,33.193,26.0019,32.5837,31.917,32.917,33.8293,Montserrat
146,Total petroleum and other liquids (Mb/d),8,8,9,10,11,11,6.1,5.6,8.2,...,21.982,22.474,23.892,28.595,25.458,24.423,28.785,28.785,28.785,New Caledonia
154,Total petroleum and other liquids (Mb/d),0,0,0,0,0,0,0,0,0,...,4,3.23934,3,1.81776,2,2,2,2,2,Northern Mariana Islands
162,Total petroleum and other liquids (Mb/d),0,0,0,4,7,8,8,7,5,...,0,0,0,0,0,0,0,0,0,Peru
170,Total petroleum and other liquids (Mb/d),0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Russia
178,Total petroleum and other liquids (Mb/d),0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Sao Tome and Principe
186,Total petroleum and other liquids (Mb/d),32,26,30,28,27,26,23,24,24,...,49.2543,57.5944,65.2012,69.0017,74.0695,77.6349,77.4659,77.633,78.1289,Slovenia
194,Total petroleum and other liquids (Mb/d),--,--,--,--,--,--,--,--,--,...,0.07,0.131,0.258,0.219,0.248,0.248,0.248,0.248,0.248,Sudan
202,Total petroleum and other liquids (Mb/d),0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Thailand
210,Total petroleum and other liquids (Mb/d),245,283,348,460,614,734,740,768,751,...,2699.13,2669.12,2713.47,2970.68,3186.49,3242.96,3366.45,3427.78,3673.66,Turkmenistan
218,Total petroleum and other liquids (Mb/d),0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,United Arab Emirates
226,Total petroleum and other liquids (Mb/d),270,188,179,187,175,168,181,150,148,...,169.377,158.731,135.49,126.807,127.004,121.034,113.313,111.623,121.56,Wake Island
234,Total petroleum and other liquids (Mb/d),3,3,3,3,4,6,-0.2,0.0978927,-1.5,...,3.367,3.799,4.095,3.23719,5.076,5.339,5.339,5.339,5.339,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1610,Total petroleum and other liquids (Mb/d),0,0,0,0,0,0,0.0166217,0.0782474,0.0320238,...,0,0,0,0,0,0,0,0,0,NaN
1618,Total petroleum and other liquids (Mb/d),1.3,2.3,12,18,30,53,52,49,53,...,448.98,489.727,498.293,498.321,520.401,531.329,515.472,516.905,512.122,NaN
1626,Total petroleum and other liquids (Mb/d),0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
1634,Total petroleum and other liquids (Mb/d),--,--,--,--,--,--,--,--,--,...,83.7425,79.4945,79.2575,74.2329,62.0603,49.2377,40.3178,32.9068,27.8274,NaN
1642,Total petroleum and other liquids (Mb/d),0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
1650,Total petroleum and other liquids (Mb/d),0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
1658,Total petroleum and other liquids (Mb/d),214,243,183,163,173,178,166,156,156,...,135.631,116.003,114.602,112.764,109.53,97.7256,99.4882,88.137,82.9611,NaN
1666,Total petroleum and other liquids (Mb/d),110,118,120,120,120,114,111,109,108,...,67.0981,65.7193,63.6019,53.0863,39.634,41.634,42.2504,41.0641,39.0395,NaN
1674,Total petroleum and other liquids (Mb/d),41,44,46,41,40,40,45,48,46,...,56.517,58.3868,57.8888,57.3672,64.0466,66.3083,67.2096,72.9685,75.6315,NaN
1682,Total petroleum and other liquids (Mb/d),--,--,--,--,--,--,--,--,--,...,224.198,245.143,261.528,274.858,278.716,266.427,280.648,279.823,243.626,NaN
1690,Total petroleum and other liquids (Mb/d),0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
1698,Total petroleum and other liquids (Mb/d),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1706,Total petroleum and other liquids (Mb/d),0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
1714,Total petroleum and other liquids (Mb/d),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1722,Total petroleum and other liquids (Mb/d),0,0,0,-1,-0.6,0.2,-5.5,-4.1,-3,...,16.553,8.085,0,0,0,0,0,0,0,NaN
1730,Total petroleum and other liquids (Mb/d),0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
1738,Total petroleum and other liquids (Mb/d),--,--,--,--,--,--,--,--,--,...,79.5976,81.0347,74.7817,65.875,59.269,55.8324,53.2468,56.1756,60.255,NaN
1746,Total petroleum and other liquids (Mb/d),1747,1538,1343,1272,1279,1356,1515,1686,1695,...,3216.54,3401.34,3442.49,3544.97,3680.59,3772.79,3728.32,3790.62,4013.51,NaN
1754,Total petroleum and other liquids (Mb/d),1674,1874,2164,2430,2652,2711,2735,2613,2443,...,1169.68,1009.29,934.348,921.624,1020.78,1083.93,1071.82,1153.96,1169.96,NaN
1762,Total petroleum and other liquids (Mb/d),10809,10739,10783,10788,11107,11192,10905,10648,10473,...,10150.3,11140.3,12394.2,14155.2,15147.1,14837.6,15647.2,17936.1,19511.9,NaN
1770,Total petroleum and other liquids (Mb/d),0,0,0,0,0,0,0.2,0.2,0.1,...,1.517,1.741,2.189,2.365,2.179,2.217,2.217,2.217,2.217,NaN
1778,Total petroleum and other liquids (Mb/d),--,--,--,--,--,--,--,--,--,...,102.677,102.569,94.676,83.9868,78.6895,71.4706,63.6183,55.8046,54.8868,NaN
1786,Total petroleum and other liquids (Mb/d),0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
1794,Total petroleum and other liquids (Mb/d),2246,2177,1973,1874,1872,1757,1890,1857,2008,...,2684.09,2686.08,2684.78,2686.6,2590.44,2355.42,2078.32,1541.59,929.008,NaN
1802,Total petroleum and other liquids (Mb/d),0,0,0,0,0,0,0.8,5,15,...,315.89,345.09,348.015,319.86,344.666,313.633,283.136,253.72,236.077,NaN
1810,Total petroleum and other liquids (Mb/d),0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
1818,Total petroleum and other liquids (Mb/d),0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
1826,Total petroleum and other liquids (Mb/d),0,0,0,0,0,0,8.6,19,172,...,216.76,169.001,130.804,125.101,47.893,21.9597,12.5533,33.8135,43.8135,NaN
1834,Total petroleum and other liquids (Mb/d),0,0,0,0,0,0,0.1,0.2,0.5,...,0.186,0.199,0.164,0.186,0.17,0.17,0.17,0.17,0.17,NaN
1842,Total petroleum and other liquids (Mb/d),0,0,0,0,0,0,0,0,0,...,0,0.12,0.039,0.681,0.714,0.819,0.819,0.819,0.819,NaN

In [155]:
# Now we export all three datasets and then in Excel/Flourish add them together to make the visuals.
Meh.to_csv('test.csv',index=False)

In [162]:
CountriesList.to_csv('country.csv',index=False)

In [165]:
TimeList.to_csv('time.csv', index=False)