## Luis Gonzalez 
## Python code to create Top 15 Most Successful Anime Movies (1988-2020)

Youtube Name: Top 15 Most Successful Anime Movies (1988-2020)

This video shows the Top 15 most successful Anime Movies that have been made in the past 32 years. The Anime movies picked had to be grossing higher than 45 million Dollars to be considered on this list. As we can see, over time, more Production companies have joined the Anime Movie industry and have contributed to creating more expensive movies.


Data Source: List of highest-grossing anime films. (n.d.) Wikipedia. Retrieved 7th May 2020 from https://en.wikipedia.org/wiki/List_of_highest-grossing_anime_films

mentatdgt. (2018). Pikachu Image. Pexels. Retrieved 7th May 2020 from https://www.pexels.com/es-es/foto/accion-actuacion-al-aire-libre-amarillo-1049622/


Song: Summer - Benjamin Tissot Available at https://www.bensound.com/royalty-free-music/track/summer-chill-relaxed-tropical

Feel free to Subscribe to my Channel: https://www.youtube.com/channel/UCNtj4VeZTSloN57mn74-RHw?view_as=subscriber

Follow my Github for a Step-By-Step guide on how to build these types of visuals. (https://github.com/LuisEGV) 

Final Ranking (2020):

1.Your Name	359275409	2016

2.Spirited Away	347742810	2001

3.Howl's Moving Castle	235184110	2004

4.Ponyo	203204882	2008

5.Weathering with You	192704855	2019

6.Stand by Me Doraemon	183442714	2014

7.Pokémon: The First Movie	172744662	1998

8.Princess Mononoke	160799185	1997

9.The Secret World of Arrietty	145570827	2010

10.The Wind Rises	136333220	2013

11.Pokémon: The Movie 2000	133949270	1999

12.Dragon Ball Super: Broly	124500000	2018

13.Detective Conan: The Fist of Blue Sapphire	119875024	2019

14.Detective Conan: Zero the Enforcer	108105223	2018

15.One Piece: Stampede	94684223	2019

In [1]:
# We will be using Pandas for reading al the relevant datasets.
import pandas as pd

In [23]:
# Here we read the data from the Energy Dataset
df = pd.read_excel('AnimeListWiki.xlsx')
# We make a time range

In [24]:
df.head()

   Rank                 Title  Worldwide gross  Year     Ref
0     1             Your Name        359275409  2016  [4][5]
1     2         Spirited Away        347742810  2001     [6]
2     3  Howl's Moving Castle        235184110  2004     [7]
3     4                 Ponyo        203204882  2008     [8]
4     5  Weathering with You         192704855  2019     [b]

In [25]:
df = df.drop('Ref', axis=1)
df.head()

   Rank                 Title  Worldwide gross  Year
0     1             Your Name        359275409  2016
1     2         Spirited Away        347742810  2001
2     3  Howl's Moving Castle        235184110  2004
3     4                 Ponyo        203204882  2008
4     5  Weathering with You         192704855  2019

In [113]:
df = df.sort_values(["Year"])
df["Year"].unique()

array([1988, 1992, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005,
       2006, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017,
       2018, 2019], dtype=int64)

In [40]:
df.iloc[0,3]

1988

In [35]:
timelist = list(range(min(df["Year"]),max(df["Year"])+1))

In [102]:
MovieYearRelease = []

FullGrossList = []


for i in range(len(timelist)):
    yearList = []
    for j in range(len(df)):
        if df.iloc[j,3] <= timelist[i]:
            yearList.append(df.iloc[j,2])
            if df.iloc[j,3] == timelist[i]:
                MovieYearRelease.append(df.iloc[j,1])
        else:
            yearList.append(0)
    FullGrossList.append(yearList)

In [103]:
MovieYearRelease

['My Neighbor Totoro\xa0',
 'Akira',
 'Porco Rosso',
 'Princess Mononoke',
 'Pokémon: The First Movie',
 'Pokémon: The Movie 2000',
 'Pokémon 3: The Movie',
 'Spirited Away',
 'The Cat Returns',
 'Pokémon: Jirachi Wish Maker',
 "Howl's Moving Castle",
 'Pokémon: Destiny Deoxys',
 'Pokémon: Lucario and the Mystery of Mew',
 'Tales from Earthsea',
 'Ponyo',
 'Pokémon: Arceus and the Jewel of Life',
 'One Piece Film: Strong World',
 'The Secret World of Arrietty',
 'Pokémon Zoroark: Master of Illusions',
 'From Up on Poppy Hill',
 'Pokémon: Black and White',
 'Detective Conan: Quarter of Silence',
 'Evangelion: 3.0 You Can (Not) Redo',
 'Pokémon the Movie: Kyurem vs. the Sword of Justice',
 'Doraemon: Nobita and the Island of Miracles—Animal Adventure',
 'One Piece Film: Z',
 'Wolf Children',
 'Detective Conan: The Eleventh Striker',
 'Dragon Ball Z: Battle of Gods',
 "Doraemon: Nobita's Secret Gadget Museum",
 'The Wind Rises',
 'Lupin the 3rd vs. Detective Conan: The Movie',
 'Yo-kai Watch: The Movie',
 'Stand by Me Doraemon',
 'Detective Conan: Sunflowers of Inferno',
 'Yo-kai Watch: Enma Daiō and the Five Tales, Meow!',
 "Dragon Ball Z: Resurrection 'F'",
 'Detective Conan: The Darkest Nightmare',
 'Doraemon: Nobita and the Birth of Japan 2016',
 'Your Name',
 'One Piece Film: Gold',
 'Detective Conan: The Crimson Love Letter',
 "Doraemon: Nobita's Great Adventure in the Antarctic Kachi Kochi",
 "Doraemon: Nobita's Treasure Island",
 'Detective Conan: Zero the Enforcer',
 'Dragon Ball Super: Broly\xa0',
 'Detective Conan: The Fist of Blue Sapphire\xa0',
 "Doraemon: Nobita's Chronicle of the Moon Exploration\xa0",
 'One Piece: Stampede\xa0',
 'Weathering with You\xa0']

In [116]:
dfObj = pd.DataFrame(FullGrossList).T

In [117]:
dfObj["Movies"] = MovieYearRelease

In [118]:
dfObj

,0,1,2,3,4,5,6,7,8,9,...,23,24,25,26,27,28,29,30,31,Movies
0,45043225,45043225,45043225,45043225,45043225,45043225,45043225,45043225,45043225,45043225,...,45043225,45043225,45043225,45043225,45043225,45043225,45043225,45043225,45043225,My Neighbor Totoro
1,49000000,49000000,49000000,49000000,49000000,49000000,49000000,49000000,49000000,49000000,...,49000000,49000000,49000000,49000000,49000000,49000000,49000000,49000000,49000000,Akira
2,0,0,0,0,58990641,58990641,58990641,58990641,58990641,58990641,...,58990641,58990641,58990641,58990641,58990641,58990641,58990641,58990641,58990641,Porco Rosso
3,0,0,0,0,0,0,0,0,0,160799185,...,160799185,160799185,160799185,160799185,160799185,160799185,160799185,160799185,160799185,Princess Mononoke
4,0,0,0,0,0,0,0,0,0,0,...,172744662,172744662,172744662,172744662,172744662,172744662,172744662,172744662,172744662,Pokémon: The First Movie
5,0,0,0,0,0,0,0,0,0,0,...,133949270,133949270,133949270,133949270,133949270,133949270,133949270,133949270,133949270,Pokémon: The Movie 2000
6,0,0,0,0,0,0,0,0,0,0,...,70157342,70157342,70157342,70157342,70157342,70157342,70157342,70157342,70157342,Pokémon 3: The Movie
7,0,0,0,0,0,0,0,0,0,0,...,347742810,347742810,347742810,347742810,347742810,347742810,347742810,347742810,347742810,Spirited Away
8,0,0,0,0,0,0,0,0,0,0,...,53918847,53918847,53918847,53918847,53918847,53918847,53918847,53918847,53918847,The Cat Returns
9,0,0,0,0,0,0,0,0,0,0,...,56386031,56386031,56386031,56386031,56386031,56386031,56386031,56386031,56386031,Pokémon: Jirachi Wish Maker
10,0,0,0,0,0,0,0,0,0,0,...,235184110,235184110,235184110,235184110,235184110,235184110,235184110,235184110,235184110,Howl's Moving Castle
11,0,0,0,0,0,0,0,0,0,0,...,54882404,54882404,54882404,54882404,54882404,54882404,54882404,54882404,54882404,Pokémon: Destiny Deoxys
12,0,0,0,0,0,0,0,0,0,0,...,53879985,53879985,53879985,53879985,53879985,53879985,53879985,53879985,53879985,Pokémon: Lucario and the Mystery of Mew
13,0,0,0,0,0,0,0,0,0,0,...,68673565,68673565,68673565,68673565,68673565,68673565,68673565,68673565,68673565,Tales from Earthsea
14,0,0,0,0,0,0,0,0,0,0,...,203204882,203204882,203204882,203204882,203204882,203204882,203204882,203204882,203204882,Ponyo
15,0,0,0,0,0,0,0,0,0,0,...,50673078,50673078,50673078,50673078,50673078,50673078,50673078,50673078,50673078,Pokémon: Arceus and the Jewel of Life
16,0,0,0,0,0,0,0,0,0,0,...,61221810,61221810,61221810,61221810,61221810,61221810,61221810,61221810,61221810,One Piece Film: Strong World
17,0,0,0,0,0,0,0,0,0,0,...,145570827,145570827,145570827,145570827,145570827,145570827,145570827,145570827,145570827,The Secret World of Arrietty
18,0,0,0,0,0,0,0,0,0,0,...,71143529,71143529,71143529,71143529,71143529,71143529,71143529,71143529,71143529,Pokémon Zoroark: Master of Illusions
19,0,0,0,0,0,0,0,0,0,0,...,61459425,61459425,61459425,61459425,61459425,61459425,61459425,61459425,61459425,From Up on Poppy Hill
20,0,0,0,0,0,0,0,0,0,0,...,57082491,57082491,57082491,57082491,57082491,57082491,57082491,57082491,57082491,Pokémon: Black and White
21,0,0,0,0,0,0,0,0,0,0,...,47024973,47024973,47024973,47024973,47024973,47024973,47024973,47024973,47024973,Detective Conan: Quarter of Silence
22,0,0,0,0,0,0,0,0,0,0,...,0,67021068,67021068,67021068,67021068,67021068,67021068,67021068,67021068,Evangelion: 3.0 You Can (Not) Redo
23,0,0,0,0,0,0,0,0,0,0,...,0,46008255,46008255,46008255,46008255,46008255,46008255,46008255,46008255,Pokémon the Movie: Kyurem vs. the Sword of Jus...
24,0,0,0,0,0,0,0,0,0,0,...,0,47043183,47043183,47043183,47043183,47043183,47043183,47043183,47043183,Doraemon: Nobita and the Island of Miracles—An...
25,0,0,0,0,0,0,0,0,0,0,...,0,88760381,88760381,88760381,88760381,88760381,88760381,88760381,88760381,One Piece Film: Z
26,0,0,0,0,0,0,0,0,0,0,...,0,54999779,54999779,54999779,54999779,54999779,54999779,54999779,54999779,Wolf Children
27,0,0,0,0,0,0,0,0,0,0,...,0,44068406,44068406,44068406,44068406,44068406,44068406,44068406,44068406,Detective Conan: The Eleventh Striker
28,0,0,0,0,0,0,0,0,0,0,...,0,0,50353002,50353002,50353002,50353002,50353002,50353002,50353002,Dragon Ball Z: Battle of Gods
29,0,0,0,0,0,0,0,0,0,0,...,0,0,46111353,46111353,46111353,46111353,46111353,46111353,46111353,Doraemon: Nobita's Secret Gadget Museum
30,0,0,0,0,0,0,0,0,0,0,...,0,0,136333220,136333220,136333220,136333220,136333220,136333220,136333220,The Wind Rises
31,0,0,0,0,0,0,0,0,0,0,...,0,0,45281157,45281157,45281157,45281157,45281157,45281157,45281157,Lupin the 3rd vs. Detective Conan: The Movie
32,0,0,0,0,0,0,0,0,0,0,...,0,0,0,80268947,80268947,80268947,80268947,80268947,80268947,Yo-kai Watch: The Movie
33,0,0,0,0,0,0,0,0,0,0,...,0,0,0,183442714,183442714,183442714,183442714,183442714,183442714,Stand by Me Doraemon
34,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,60985674,60985674,60985674,60985674,60985674,Detective Conan: Sunflowers of Inferno
35,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,58850969,58850969,58850969,58850969,58850969,"Yo-kai Watch: Enma Daiō and the Five Tales, Meow!"
36,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,72636999,72636999,72636999,72636999,72636999,Dragon Ball Z: Resurrection 'F'
37,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,66280000,66280000,66280000,66280000,Detective Conan: The Darkest Nightmare
38,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,58400000,58400000,58400000,58400000,Doraemon: Nobita and the Birth of Japan 2016
39,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,359275409,359275409,359275409,359275409,Your Name
40,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,70840000,70840000,70840000,70840000,One Piece Film: Gold
41,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,64450000,64450000,64450000,Detective Conan: The Crimson Love Letter
42,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,65500000,65500000,65500000,Doraemon: Nobita's Great Adventure in the Anta...
43,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,83812757,83812757,Doraemon: Nobita's Treasure Island
44,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,108105223,108105223,Detective Conan: Zero the Enforcer
45,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,124500000,124500000,Dragon Ball Super: Broly
46,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,119875024,Detective Conan: The Fist of Blue Sapphire
47,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,65406606,Doraemon: Nobita's Chronicle of the Moon Explo...
48,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,94684223,One Piece: Stampede
49,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,192704855,Weathering with You

In [120]:
# Now we export all three datasets and then in Excel/Flourish add them together to make the visuals.
dfObj.to_csv('AnimeList.csv',index=False)

In [122]:
df.sort_values(["Worldwide gross"])

,Rank,Title,Worldwide gross,Year
49,50,Detective Conan: The Eleventh Striker,44068406,2012
48,49,My Neighbor Totoro,45043225,1988
47,48,Lupin the 3rd vs. Detective Conan: The Movie,45281157,2013
46,47,Pokémon the Movie: Kyurem vs. the Sword of Jus...,46008255,2012
45,46,Doraemon: Nobita's Secret Gadget Museum,46111353,2013
44,45,Detective Conan: Quarter of Silence,47024973,2011
43,44,Doraemon: Nobita and the Island of Miracles—An...,47043183,2012
42,43,Akira,49000000,1988
41,42,Dragon Ball Z: Battle of Gods,50353002,2013
40,41,Pokémon: Arceus and the Jewel of Life,50673078,2009
39,40,Pokémon: Lucario and the Mystery of Mew,53879985,2005
38,39,The Cat Returns,53918847,2002
37,38,Pokémon: Destiny Deoxys,54882404,2004
36,37,Wolf Children,54999779,2012
35,36,Pokémon: Jirachi Wish Maker,56386031,2003
34,35,Pokémon: Black and White,57082491,2011
33,34,Doraemon: Nobita and the Birth of Japan 2016,58400000,2016
32,33,"Yo-kai Watch: Enma Daiō and the Five Tales, Meow!",58850969,2015
31,32,Porco Rosso,58990641,1992
30,31,Detective Conan: Sunflowers of Inferno,60985674,2015
29,30,One Piece Film: Strong World,61221810,2009
28,29,From Up on Poppy Hill,61459425,2011
27,28,Detective Conan: The Crimson Love Letter,64450000,2017
26,27,Doraemon: Nobita's Chronicle of the Moon Explo...,65406606,2019
25,26,Doraemon: Nobita's Great Adventure in the Anta...,65500000,2017
24,25,Detective Conan: The Darkest Nightmare,66280000,2016
23,24,Evangelion: 3.0 You Can (Not) Redo,67021068,2012
22,23,Tales from Earthsea,68673565,2006
21,22,Pokémon 3: The Movie,70157342,2000
20,21,One Piece Film: Gold,70840000,2016
19,20,Pokémon Zoroark: Master of Illusions,71143529,2010
18,19,Dragon Ball Z: Resurrection 'F',72636999,2015
17,18,Yo-kai Watch: The Movie,80268947,2014
16,17,Doraemon: Nobita's Treasure Island,83812757,2018
15,16,One Piece Film: Z,88760381,2012
14,15,One Piece: Stampede,94684223,2019
13,14,Detective Conan: Zero the Enforcer,108105223,2018
12,13,Detective Conan: The Fist of Blue Sapphire,119875024,2019
11,12,Dragon Ball Super: Broly,124500000,2018
10,11,Pokémon: The Movie 2000,133949270,1999
9,10,The Wind Rises,136333220,2013
8,9,The Secret World of Arrietty,145570827,2010
7,8,Princess Mononoke,160799185,1997
6,7,Pokémon: The First Movie,172744662,1998
5,6,Stand by Me Doraemon,183442714,2014
4,5,Weathering with You,192704855,2019
3,4,Ponyo,203204882,2008
2,3,Howl's Moving Castle,235184110,2004
1,2,Spirited Away,347742810,2001
0,1,Your Name,359275409,2016